# Generated by Django 5.2.17 on 2026-08-15 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('material', 'Material'), ('checkpoint_question', 'Checkpoint Question')], max_length=30)),
                ('scope_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_thread',
            },
        ),
        migrations.CreateModel(
            name='LearningConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_concept',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_goal',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.IntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'learning_material',
            },
        ),
        migrations.CreateModel(
            name='UsersUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.chatthread')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learning.learningconcept')),
            ],
            options={
                'db_table': 'assessment_skill',
            },
        ),
        migrations.AddField(
            model_name='learningconcept',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='learning.learninggoal'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='learning.learningmaterial'),
        ),
        migrations.CreateModel(
            name='ProgressLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('example', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningconcept')),
            ],
            options={
                'db_table': 'progress_lesson',
            },
        ),
        migrations.CreateModel(
            name='ProgressLessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning.progresslesson')),
            ],
            options={
                'db_table': 'progress_lesson_card',
            },
        ),
        migrations.CreateModel(
            name='ProgressPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningconcept')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial')),
            ],
            options={
                'db_table': 'progress_path_step',
            },
        ),
        migrations.AddField(
            model_name='progresslesson',
            name='step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='learning.progresspathstep'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30)),
                ('after_card_order', models.IntegerField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.progresslesson')),
            ],
            options={
                'db_table': 'quiz_question',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.quizquestion')),
            ],
            options={
                'db_table': 'quiz_option',
            },
        ),
        migrations.CreateModel(
            name='QuizHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('hint_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion')),
            ],
            options={
                'db_table': 'quiz_hint',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('hints_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quizquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'quiz_attempt',
            },
        ),
        migrations.CreateModel(
            name='ProgressStudentStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.progresspathstep')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'progress_student_step_status',
            },
        ),
        migrations.CreateModel(
            name='ProgressStudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'progress_student_material_progress',
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser'),
        ),
        migrations.CreateModel(
            name='AssessmentSkillCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_known', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assessmentskill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'assessment_skill_check',
            },
        ),
        migrations.AddConstraint(
            model_name='learningconcept',
            constraint=models.UniqueConstraint(fields=('goal', 'external_id'), name='learning_concept_goal_id_external_id_key'),
        ),
        migrations.AddConstraint(
            model_name='progresslessoncard',
            constraint=models.UniqueConstraint(fields=('lesson', 'order_index'), name='progress_lesson_card_lesson_id_order_index_key'),
        ),
        migrations.AddConstraint(
            model_name='progresspathstep',
            constraint=models.UniqueConstraint(fields=('material', 'concept'), name='progress_path_step_material_id_concept_id_key'),
        ),
        migrations.AddConstraint(
            model_name='progresspathstep',
            constraint=models.UniqueConstraint(fields=('material', 'order_index'), name='progress_path_step_material_id_order_index_key'),
        ),
        migrations.AddConstraint(
            model_name='quizhint',
            constraint=models.UniqueConstraint(fields=('question', 'level'), name='quiz_hint_question_id_level_key'),
        ),
        migrations.AddConstraint(
            model_name='progressstudentstepstatus',
            constraint=models.UniqueConstraint(fields=('student', 'step'), name='progress_student_step_status_student_id_step_id_key'),
        ),
        migrations.AddConstraint(
            model_name='progressstudentmaterialprogress',
            constraint=models.UniqueConstraint(fields=('student', 'material'), name='progress_student_material_progress_student_id_material_id_key'),
        ),
        migrations.AddConstraint(
            model_name='assessmentskillcheck',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='assessment_skill_check_student_id_skill_id_key'),
        ),
    ]
