# Generated by Django 5.2.17 on 2026-08-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='学習教材本文 / 課題内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '学習教材',
                'verbose_name_plural': '学習教材一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='学習目標')),
                ('description', models.TextField(blank=True, verbose_name='目標の詳細・達成基準')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='learning.learningmaterial', verbose_name='関連教材')),
            ],
            options={
                'verbose_name': '学習目標',
                'verbose_name_plural': '学習目標一覧',
                'ordering': ['created_at'],
            },
        ),
    ]
