# Generated by Django 5.2.17 on 2026-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='scope_type',
            field=models.CharField(choices=[('material', 'Material'), ('goal', 'Goal'), ('checkpoint_question', 'Checkpoint Question')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('student', 'scope_type', 'scope_id'), name='chat_thread_student_scope_unique'),
        ),
    ]
