# Generated by Django 6.1 on 2026-08-12 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終利用日時'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='進捗率(%)'),
        ),
    ]
