# Generated by Django 5.2.17 on 2026-08-14 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('material', 'Material'), ('checkpoint_question', 'Checkpoint Question')], max_length=30)),
                ('scope_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_thread',
            },
        ),
        migrations.CreateModel(
            name='UsersUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.AlterModelOptions(
            name='learninggoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='learninggoal',
            table='learning_goal',
        ),
        migrations.AlterModelTable(
            name='learningmaterial',
            table='learning_material',
        ),
        migrations.CreateModel(
            name='AssessmentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learninggoal')),
            ],
            options={
                'db_table': 'assessment_skill',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.chatthread')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.CreateModel(
            name='ProgressPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial')),
            ],
            options={
                'db_table': 'progress_path_step',
            },
        ),
        migrations.CreateModel(
            name='ProgressLessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.progresspathstep')),
            ],
            options={
                'db_table': 'progress_lesson_card',
            },
        ),
        migrations.CreateModel(
            name='QuizCheckpointQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_card_order', models.IntegerField()),
                ('question_text', models.TextField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.progresspathstep')),
            ],
            options={
                'db_table': 'quiz_checkpoint_question',
            },
        ),
        migrations.CreateModel(
            name='QuizCheckpointOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizcheckpointquestion')),
            ],
            options={
                'db_table': 'quiz_checkpoint_option',
            },
        ),
        migrations.CreateModel(
            name='QuizFinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial')),
            ],
            options={
                'db_table': 'quiz_final_test',
            },
        ),
        migrations.CreateModel(
            name='QuizFinalTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('question_text', models.TextField()),
                ('explanation', models.TextField()),
                ('final_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizfinaltest')),
            ],
            options={
                'db_table': 'quiz_final_test_question',
            },
        ),
        migrations.CreateModel(
            name='QuizFinalTestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizfinaltestquestion')),
            ],
            options={
                'db_table': 'quiz_final_test_option',
            },
        ),
        migrations.CreateModel(
            name='QuizHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('hint_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizcheckpointquestion')),
            ],
            options={
                'db_table': 'quiz_hint',
            },
        ),
        migrations.CreateModel(
            name='QuizTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('attempt_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizfinaltest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'quiz_test_attempt',
            },
        ),
        migrations.CreateModel(
            name='QuizCheckpointAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('hints_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.quizcheckpointoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizcheckpointquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'quiz_checkpoint_attempt',
            },
        ),
        migrations.CreateModel(
            name='ProgressStudentStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.progresspathstep')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'progress_student_step_status',
            },
        ),
        migrations.CreateModel(
            name='ProgressStudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'progress_student_material_progress',
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser'),
        ),
        migrations.CreateModel(
            name='AssessmentSkillCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_known', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assessmentskill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.usersuser')),
            ],
            options={
                'db_table': 'assessment_skill_check',
            },
        ),
        migrations.AddConstraint(
            model_name='progresspathstep',
            constraint=models.UniqueConstraint(fields=('material', 'order_index'), name='unique_material_order'),
        ),
        migrations.AddConstraint(
            model_name='progresslessoncard',
            constraint=models.UniqueConstraint(fields=('step', 'order_index'), name='unique_step_order'),
        ),
        migrations.AddConstraint(
            model_name='quizfinaltestquestion',
            constraint=models.UniqueConstraint(fields=('final_test', 'order_index'), name='unique_final_test_order'),
        ),
        migrations.AddConstraint(
            model_name='quizhint',
            constraint=models.UniqueConstraint(fields=('question', 'level'), name='unique_question_hint_level'),
        ),
        migrations.AddConstraint(
            model_name='progressstudentstepstatus',
            constraint=models.UniqueConstraint(fields=('student', 'step'), name='unique_student_step'),
        ),
        migrations.AddConstraint(
            model_name='progressstudentmaterialprogress',
            constraint=models.UniqueConstraint(fields=('student', 'material'), name='unique_student_material'),
        ),
        migrations.AddConstraint(
            model_name='assessmentskillcheck',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill'),
        ),
    ]
