# Generated by Django 6.1 on 2026-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningmaterial_last_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English')], default='math', max_length=20, verbose_name='教科'),
        ),
    ]
