# Generated by Django 5.2.17 on 2026-08-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_chatthread_usersuser_alter_learninggoal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='learning.learningmaterial'),
        ),
    ]
