# Generated by Django 5.2.17 on 2026-08-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_chatthread_scope_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.usersuser'),
        ),
    ]
