# Generated by Django 6.1 on 2026-08-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningmaterial_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='ファイル')),
                ('name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('size', models.BigIntegerField(default=0, verbose_name='ファイルサイズ(Byte)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('learning_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='learning.learningmaterial')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
