# Generated by Django 6.1 on 2026-08-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_uploadeddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'ordering': ['-created_at'], 'verbose_name': '学習目標', 'verbose_name_plural': '学習目標一覧'},
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['-last_used_at']},
        ),
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={},
        ),
    ]
