# Generated by Django 6.1 on 2026-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_learninggoal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='トピック名')),
                ('subject', models.CharField(default='math', max_length=20, verbose_name='教科')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'トピック',
                'verbose_name_plural': 'トピック一覧',
            },
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['-last_used_at'], 'verbose_name': '学習教材', 'verbose_name_plural': '学習教材一覧'},
        ),
    ]
