# Generated by Django 6.1 on 2026-08-14 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_topic_alter_learningmaterial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新しいチャット', max_length=255, verbose_name='スレッドタイトル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('learning_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='learning.learningmaterial')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'ユーザー'), ('ai', 'AIアシスタント')], max_length=10, verbose_name='送信者')),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
