# Generated by Django 6.1 on 2026-08-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_learninggoal_material'),
        ('learning', '0008_userstepprogress'),
    ]

    operations = [
    ]
