# Generated by Django 5.2.17 on 2026-08-14 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_merge_20260814_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'ordering': ['-created_at'], 'verbose_name': '学習目標', 'verbose_name_plural': '学習目標一覧'},
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['-last_used_at'], 'verbose_name': '学習教材', 'verbose_name_plural': '学習教材一覧'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'ユーザー'), ('ai', 'AIアシスタント')], default='user', max_length=10, verbose_name='送信者'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='learning_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='learning.learningmaterial'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='title',
            field=models.CharField(default='新しいチャット', max_length=255, verbose_name='スレッドタイトル'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='メッセージ内容'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('ai', 'AI')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.chatthread'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='scope_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='scope_type',
            field=models.CharField(choices=[('material', 'Material'), ('checkpoint_question', 'Checkpoint Question')], default='material', max_length=30),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='目標の詳細・達成基準'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200, verbose_name='学習目標'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(verbose_name='学習教材本文 / 課題内容'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
