from django.urls import path
from . import views

app_name = "learning"
app_name = 'learning'

urlpatterns = [
    # 🏠 ログイン前トップページ
    path('', views.index, name='index'),
    
    # 📊 ログイン後ダッシュボード（追加！）
    path('dashboard/', views.dashboard, name='dashboard'),
    
    # 教科選択などその他の設定...
    path('subjects/', views.subject_select, name='subject_select'),
    path('topics/<str:subject>/', views.topic_list, name='topic_list'),
    path('topics/<str:subject>/add/', views.add_topic, name='add_topic'),
    path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    path('topic/<int:topic_id>/upload/', views.document_upload, name='document_upload'),
    path('topic/<int:topic_id>/edit-title/', views.edit_topic_title, name='edit_topic_title'),
    path('topic/<int:topic_id>/delete/', views.delete_topic, name='delete_topic'),
    path('topics/<str:subject>/batch-delete/', views.batch_delete_topics, name='batch_delete_topics'),
    path('topic/<int:topic_id>/save-understanding/', views.save_understanding, name='save_understanding'),
    path('topic/<int:topic_id>/path-map/', views.path_map_view, name='path_map'),
    path('finaltest/', views.finaltest, name='finaltest'),
    path('chat/', views.chat_thread_list, name='chat_thread_list'),
    path('chat/<int:thread_id>/', views.chat_detail, name='chat_detail'),
    path('chat/<int:thread_id>/send/', views.send_chat_message, name='send_chat_message'),
    path('chat/create/<int:topic_id>/', views.create_chat_thread, name='create_chat_thread'),
    path('topic/<int:topic_id>/step/<int:step_num>/', views.lesson_card_view, name='lesson_card'),
    path('topic/<int:topic_id>/step/<int:step_num>/checkpoint/', views.lesson_checkpoint_view, name='lesson_checkpoint'),
    path('topic/<int:topic_id>/step/<int:step_num>/complete/', views.complete_step_api, name='complete_step_api'),
    path('api/topic/<int:topic_id>/step/<int:step_num>/complete/', views.complete_step_api, name='complete_step_api'),
    path('settings/update/', views.update_settings, name='update_settings'),
    path('settings/', views.settings_view, name='settings'),
    path('profile/', views.profile_view, name='profile'),
    path("", views.index, name="index"),
    path("navigation.js", views.frontend_navigation_js, name="frontend_navigation_js"),
    path("api.js", views.frontend_api_js, name="frontend_api_js"),
    path("lumina_learning_landing_page.html", views.frontend_page, {"page_name": "lumina_learning_landing_page.html"}, name="landing_page"),
    path("lumina_learning_login_screen.html", views.frontend_page, {"page_name": "lumina_learning_login_screen.html"}, name="login_page"),
    path("student_dashboard_overview.html", views.frontend_page, {"page_name": "student_dashboard_overview.html"}, name="dashboard_page"),
    path("lumina_learning_upload_document_desktop.html", views.frontend_page, {"page_name": "lumina_learning_upload_document_desktop.html"}, name="upload_page"),
    path("review_document_content_selection.html", views.frontend_page, {"page_name": "review_document_content_selection.html"}, name="review_document_page"),
    path("personalized_learning_path.html", views.frontend_page, {"page_name": "personalized_learning_path.html"}, name="learning_path_page"),
    path("interactive_lesson_linear_regression_with_sidebar.html", views.frontend_page, {"page_name": "interactive_lesson_linear_regression_with_sidebar.html"}, name="lesson_page"),
    path("new_course_ai_topic_discussion.html", views.frontend_page, {"page_name": "new_course_ai_topic_discussion.html"}, name="ai_tutor_page"),
    path("settings_user_account_preferences.html", views.frontend_page, {"page_name": "settings_user_account_preferences.html"}, name="settings_page"),
    path("course_history_my_learning_journeys_1.html", views.frontend_page, {"page_name": "course_history_my_learning_journeys_1.html"}, name="history_page"),
    path("final_test_full_screen_question_review.html", views.frontend_page, {"page_name": "final_test_full_screen_question_review.html"}, name="test_page"),
    path("final_test_result_summary_review.html", views.frontend_page, {"page_name": "final_test_result_summary_review.html"}, name="result_page"),
    path("final_test_ai_review_conversation.html", views.frontend_page, {"page_name": "final_test_ai_review_conversation.html"}, name="ai_review_page"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("material/create/", views.create_material_view, name="create_material"),
    path("materials/", views.list_materials_view, name="list_materials"),
    path("courses/", views.list_courses_view, name="list_courses"),
    path("material/<int:material_id>/", views.get_material_detail_view, name="get_material_detail"),
    path("material/<int:material_id>/delete/", views.delete_material_view, name="delete_material"),
    path("path/generate/", views.generate_path_view, name="generate_path"),
    path("step/<int:step_id>/quiz/", views.get_step_quiz_view, name="get_step_quiz"),
    path("checkpoint/submit/", views.submit_checkpoint_view, name="submit_checkpoint"),
    path("hint/<int:question_id>/<int:level>/", views.get_hint_view, name="get_hint"),
    path("chat/", views.chat_view, name="chat"),
        path('ft_result/', views.result, name='ft_result'),
    path("chat/thread/", views.create_chat_thread_view, name="create_chat_thread"),
    path("chat/threads/", views.list_user_chat_threads_view, name="list_user_chat_threads"),
    path("chat/thread/<int:thread_id>/", views.get_chat_thread_detail_view, name="get_chat_thread_detail"),
    path("chat/thread/new/", views.create_new_chat_thread_view, name="create_new_chat_thread"),
    path("auth/register/", views.register_view, name="register"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/me/", views.me_view, name="me"),
]
